#!/usr/bin/env python3

import hashlib
import base64
import os
import random


def sha256(bytes):
    s = hashlib.sha256()
    s.update(bytes)
    return s.digest()


salt = bytearray()
for i in range(0, 8):
    salt.append(random.randint(0, 255))

password = os.environ.get('PAYARA_PASSWORD')
hash = str.encode(password, 'UTF-8') + salt

for i in range(0, 100):
    hash = sha256(hash)

text = "admin;{SSHA256}" + base64.encodebytes(hash + salt).decode('UTF-8')[0:-1] + ";asadmin"
print(text)
